# @nvim.on_save deno task codex:template -- --apply
model = "gpt-5.4"
model_context_window = 1000000
model_auto_compact_token_limit = 950000
model_reasoning_effort = "high"
plan_mode_reasoning_effort = "high"
network_access = true
disable_response_storage = true
web_search = "live"
notify = [
  "vde-notifier",
  "--codex",
  "--skip-codex-subagent",
  "--skip-codex-non-interactive"
]
suppress_unstable_features_warning = true
personality = "pragmatic"

[agents]
max_threads = 32
max_depth = 2

[agents.explorer]
description = "Codebase research agent. Use for all code investigation, no edits."
config_file = "~/.codex/agents/explorer.toml"

[agents.worker]
description = "Coding and bug fix agent. Use for implementation, refactoring, and running tests."
config_file = "~/.codex/agents/worker.toml"

[features]
unified_exec = true
view_image_tool = true
shell_snapshot = true
steer = true
skills = true
collaboration_modes = true
apps = true
multi_agent = true
# voice_transcription = true
default_mode_request_user_input = true
responses_websockets_v2 = true
fast_mode = true
code_mode = true
js_repl = true
codex_hooks = true

[tui]
status_line = ["model-with-reasoning", "current-dir", "git-branch", "context-remaining", "fast-mode", "context-window-size"]
theme = "catppuccin-mocha"
