memodir = "~/.config/memo/_posts"
editor = "nvim"
column = 20
selectcmd = "peco"
 grepcmd = "ag ${PATTERN} ${DIR}"
assetsdir = "."
pluginsdir = "~/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
