[settings]
experimental = true
disable_backends = ["asdf", "vfox"]
idiomatic_version_file_enable_tools = ["node"]
minimum_release_age_excludes = ["npm:@openai/codex", "cargo:vde-tmux"]

[settings.pipx]
uvx = true

[tools]
bun = "latest"
"cargo:octorus" = "latest"
"cargo:pez" = "latest"
"cargo:similarity-ts" = "latest"
"cargo:tmux-fuzzy-motion" = "latest"
"cargo:vde-tmux" = "latest"
"cargo:vde-tmux-manager" = "latest"
go = "latest"
"go:github.com/rhysd/vim-startuptime" = "latest"
node = "latest"
"npm:@aikidosec/safe-chain" = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@playwright/cli" = "latest"
"npm:@qwen-code/qwen-code" = "latest"
"npm:agent-browser" = "latest"
"npm:cspell" = "latest"
"npm:editprompt" = "latest"
"npm:mdjanai" = "latest"
"npm:obsidian-headless" = "latest"
"npm:opensrc" = "latest"
"npm:pnpm" = "latest"
"npm:portless" = "latest"
"npm:sdd-mcp" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:uipro-cli" = "latest"
"npm:vde-layout" = "latest"
"npm:vde-monitor" = "latest"
"npm:vde-worktree" = "latest"
"npm:wrangler" = "latest"
"npm:yarn" = "latest"
"pipx:mcp-proxy-for-aws" = "latest"
python = "latest"
rust = "nightly"
uv = "latest"
