[settings]
experimental = true
disable_backends = ["asdf", "vfox"]
idiomatic_version_file_enable_tools = ["node"]

[settings.pipx]
uvx = true

[tools]
bun = "latest"
"cargo:octorus" = "latest"
"cargo:pez" = "latest"
"cargo:similarity-ts" = "latest"
node = "latest"
"npm:@aikidosec/safe-chain" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@playwright/cli" = "latest"
"npm:agent-browser" = "latest"
"npm:editprompt" = "latest"
"npm:mdjanai" = "latest"
"npm:pnpm" = "latest"
"npm:sdd-mcp" = "latest"
"npm:tmux-fuzzy-motion" = "latest"
"npm:vde-layout" = "latest"
"npm:vde-monitor" = "latest"
"npm:vde-notifier" = "latest"
"npm:vde-tmux-manager" = "latest"
"npm:vde-worktree" = "latest"
"npm:wrangler" = "latest"
"npm:yarn" = "latest"
"pipx:mcp-proxy-for-aws" = "latest"
python = "3.14"
rust = "nightly"
uv = "latest"
